# Generated by Django 2.2.11 on 2020-09-22 11:56

# stdlib
from typing import List
# libs
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('action', models.CharField(max_length=8000, null=True)),
                ('description', models.TextField(null=True)),
                ('icon_url', models.CharField(max_length=8000, null=True)),
                ('in_app_store', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('online', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('action', models.CharField(max_length=150, null=True)),
                ('administrator_only', models.BooleanField(default=False)),
                ('help', models.TextField(default='No help for this menu item', null=True)),
                ('name', models.CharField(max_length=150)),
                ('public', models.BooleanField(default=False)),
                ('self_managed', models.BooleanField(default=True)),
                ('sequence', models.IntegerField()),
                ('app', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='menu_items',
                    to='app_manager.App',
                )),
                ('predecessor', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='children',
                    to='app_manager.MenuItem',
                )),
            ],
            options={
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='MenuItemUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user_id', models.IntegerField()),
                ('menu_item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user_links',
                    to='app_manager.MenuItem',
                )),
            ],
            options={
                'db_table': 'menu_item_user_link',
            },
        ),
        migrations.CreateModel(
            name='MemberLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('member_id', models.IntegerField()),
                ('app', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='member_links',
                    to='app_manager.App',
                )),
            ],
            options={
                'db_table': 'member_link',
            },
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['id'], name='app_id'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['created'], name='app_created'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['in_app_store'], name='app_in_app_store'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['maintenance'], name='app_maintenance'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['name'], name='app_name'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['private'], name='app_private'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['updated'], name='app_updated'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemuserlink',
            unique_together={('user_id', 'menu_item')},
        ),
    ]
