# Generated by Django 5.0.10 on 2025-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='memberlink',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='memberlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitemuserlink',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='menuitemuserlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
